In [17]:
import pandas as pd
import numpy as np

In [2]:
acquisti = pd.read_csv("transactions_train.csv")
acquisti

,t_dat,customer_id,article_id,price,sales_channel_id
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2
1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,0.030492,2
2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,0.015237,2
3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,0.016932,2
4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,0.016932,2
...,...,...,...,...,...
31788319,2020-09-22,fff2282977442e327b45d8c89afde25617d00124d0f999...,929511001,0.059305,2
31788320,2020-09-22,fff2282977442e327b45d8c89afde25617d00124d0f999...,891322004,0.042356,2
31788321,2020-09-22,fff380805474b287b05cb2a7507b9a013482f7dd0bce0e...,918325001,0.043203,1
31788322,2020-09-22,fff4d3a8b1f3b60af93e78c30a7cb4cf75edaf2590d3e5...,833459002,0.006763,1
31788323,2020-09-22,fffef3b6b73545df065b521e19f64bf6fe93bfd450ab20...,898573003,0.033881,2

In [3]:
acquisti.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31788324 entries, 0 to 31788323
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   t_dat             object
 1   customer_id       object
 2   article_id        int64
 3   price             float64
 4   sales_channel_id  int64
dtypes: float64(1), int64(2), object(2)
memory usage: 1.2+ GB

In [4]:
acquisti.describe()

         article_id         price  sales_channel_id
count  3.178832e+07  3.178832e+07      3.178832e+07
mean   6.962272e+08  2.782927e-02      1.704028e+00
std    1.334480e+08  1.918113e-02      4.564786e-01
min    1.087750e+08  1.694915e-05      1.000000e+00
25%    6.328030e+08  1.581356e-02      1.000000e+00
50%    7.145820e+08  2.540678e-02      2.000000e+00
75%    7.865240e+08  3.388136e-02      2.000000e+00
max    9.562170e+08  5.915254e-01      2.000000e+00

In [5]:
articoli = pd.read_csv("articles.csv")
articoli

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105537,953450001,953450,5pk regular Placement1,302,Socks,Socks & Tights,1010014,Placement print,9,Black,...,Socks Bin,F,Menswear,3,Menswear,26,Men Underwear,1021,Socks and Tights,Socks in a fine-knit cotton blend with a small...
105538,953763001,953763,SPORT Malaga tank,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey,A,Ladieswear,1,Ladieswear,2,H&M+,1005,Jersey Fancy,Loose-fitting sports vest top in ribbed fast-d...
105539,956217002,956217,Cartwheel dress,265,Dress,Garment Full body,1010016,Solid,9,Black,...,Jersey,A,Ladieswear,1,Ladieswear,18,Womens Trend,1005,Jersey Fancy,"Short, A-line dress in jersey with a round nec..."
105540,957375001,957375,CLAIRE HAIR CLAW,72,Hair clip,Accessories,1010016,Solid,9,Black,...,Small Accessories,D,Divided,2,Divided,52,Divided Accessories,1019,Accessories,Large plastic hair claw.
105541,959461001,959461,Lounge dress,265,Dress,Garment Full body,1010016,Solid,11,Off White,...,Jersey,A,Ladieswear,1,Ladieswear,18,Womens Trend,1005,Jersey Fancy,Calf-length dress in ribbed jersey made from a...

In [6]:
articoli.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105542 entries, 0 to 105541
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   article_id                    105542 non-null  int64
 1   product_code                  105542 non-null  int64
 2   prod_name                     105542 non-null  object
 3   product_type_no               105542 non-null  int64
 4   product_type_name             105542 non-null  object
 5   product_group_name            105542 non-null  object
 6   graphical_appearance_no       105542 non-null  int64
 7   graphical_appearance_name     105542 non-null  object
 8   colour_group_code             105542 non-null  int64
 9   colour_group_name             105542 non-null  object
 10  perceived_colour_value_id     105542 non-null  int64
 11  perceived_colour_value_name   105542 non-null  object
 12  perceived_colour_master_id    105542 non-null  int64
 13  perceived_colour_master_name  105542 non-null  object
 14  department_no                 105542 non-null  int64
 15  department_name               105542 non-null  object
 16  index_code                    105542 non-null  object
 17  index_name                    105542 non-null  object
 18  index_group_no                105542 non-null  int64
 19  index_group_name              105542 non-null  object
 20  section_no                    105542 non-null  int64
 21  section_name                  105542 non-null  object
 22  garment_group_no              105542 non-null  int64
 23  garment_group_name            105542 non-null  object
 24  detail_desc                   105126 non-null  object
dtypes: int64(11), object(14)
memory usage: 20.1+ MB

In [7]:
articoli.describe()

,article_id,product_code,product_type_no,graphical_appearance_no,colour_group_code,perceived_colour_value_id,perceived_colour_master_id,department_no,index_group_no,section_no,garment_group_no
count,1.055420e+05,105542.000000,105542.000000,1.055420e+05,105542.000000,105542.000000,105542.000000,105542.000000,105542.000000,105542.000000,105542.000000
mean,6.984246e+08,698424.563378,234.861875,1.009515e+06,32.233822,3.206183,7.807972,4532.777833,3.171534,42.664219,1010.438290
std,1.284624e+08,128462.384432,75.049308,2.241359e+04,28.086154,1.563839,5.376727,2712.692011,4.353234,23.260105,6.731023
min,1.087750e+08,108775.000000,-1.000000,-1.000000e+00,-1.000000,-1.000000,-1.000000,1201.000000,1.000000,2.000000,1001.000000
25%,6.169925e+08,616992.500000,252.000000,1.010008e+06,9.000000,2.000000,4.000000,1676.000000,1.000000,20.000000,1005.000000
50%,7.022130e+08,702213.000000,259.000000,1.010016e+06,14.000000,4.000000,5.000000,4222.000000,2.000000,46.000000,1009.000000
75%,7.967030e+08,796703.000000,272.000000,1.010016e+06,52.000000,4.000000,11.000000,7389.000000,4.000000,61.000000,1017.000000
max,9.594610e+08,959461.000000,762.000000,1.010029e+06,93.000000,7.000000,20.000000,9989.000000,26.000000,97.000000,1025.000000

In [8]:
c_id = acquisti["customer_id"].values[0]
c_id

'000058a12d5b43e67d225668fa1f8d618c13dc232df0cad8ffe7ad4a1091e318'

In [14]:
lista_articoli = acquisti[acquisti["customer_id"] == c_id]["article_id"]
lista_articoli

0           663713001
1           541518023
165807      663713001
6827145     578020002
21953950    723529001
21953951    351484002
21953952    351484002
23934157    727808001
23934158    727808007
24773518    858883002
24773519    851400006
24773520    750424014
24773521    750424014
24773522    870304002
24773523    870304002
24773524    852643001
24773525    852643003
31521960    794321007
Name: article_id, dtype: int64

In [16]:
for articolo in lista_articoli:
    print(articoli[articoli["article_id"] == articolo]["product_type_name"])

40179    Underwear body
Name: product_type_name, dtype: object
10520    Bra
Name: product_type_name, dtype: object
40179    Underwear body
Name: product_type_name, dtype: object
18197    Blouse
Name: product_type_name, dtype: object
59458    Bikini top
Name: product_type_name, dtype: object
1469    Swimwear bottom
Name: product_type_name, dtype: object
1469    Swimwear bottom
Name: product_type_name, dtype: object
60253    Sweater
Name: product_type_name, dtype: object
60259    Sweater
Name: product_type_name, dtype: object
93585    Blouse
Name: product_type_name, dtype: object
91841    Skirt
Name: product_type_name, dtype: object
67274    Trousers
Name: product_type_name, dtype: object
67274    Trousers
Name: product_type_name, dtype: object
96382    Shirt
Name: product_type_name, dtype: object
96382    Shirt
Name: product_type_name, dtype: object
92158    Sweater
Name: product_type_name, dtype: object
92159    Sweater
Name: product_type_name, dtype: object
78503    Jacket
Name: product_type_name, dtype: object

Scoprire il cliente H&M che ha fatto piÃ¹ acqusti

In [42]:
lista_consumatori = acquisti["customer_id"]
lista_consumatori

0           000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...
1           000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...
2           00007d2de826758b65a93dd24ce629ed66842531df6699...
3           00007d2de826758b65a93dd24ce629ed66842531df6699...
4           00007d2de826758b65a93dd24ce629ed66842531df6699...
                                  ...
31788319    fff2282977442e327b45d8c89afde25617d00124d0f999...
31788320    fff2282977442e327b45d8c89afde25617d00124d0f999...
31788321    fff380805474b287b05cb2a7507b9a013482f7dd0bce0e...
31788322    fff4d3a8b1f3b60af93e78c30a7cb4cf75edaf2590d3e5...
31788323    fffef3b6b73545df065b521e19f64bf6fe93bfd450ab20...
Name: customer_id, Length: 31788324, dtype: object

In [43]:
unique, frequency = np.unique(lista_consumatori, return_counts = True)
# print unique values array
print("Unique Values:", unique)
  
# print frequency array
print("Frequency Values:",frequency)

n = frequency.max()

print(f"Numero piÃ¹ grande di acquisti fatti da un solo cliente: {n}")

posizione_n = frequency == n

unique[posizione_n][0] # cliente con piÃ¹ acquisti

Unique Values: ['00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d25f88aa139fdfc657'
 '0000423b00ade91418cceaf3b26c6af3dd342b51fd051eec9c12fb36984420fa'
 '000058a12d5b43e67d225668fa1f8d618c13dc232df0cad8ffe7ad4a1091e318' ...
 'ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1778d0116cffd259264'
 'ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38b2236865d949d4df6a'
 'ffffd9ac14e89946416d80e791d064701994755c3ab686a1eaf3458c36f52241']
Frequency Values: [21 86 18 ... 45  7  1]
Numero piÃ¹ grande di acquisti fatti da un solo cliente: 1895

'be1981ab818cf4ef6765b2ecaea7a2cbf14ccd6e8a7ee985513d9e8e53c6d91b'

Scoprire il cliente di H&M che ha acquistato il set di articoli dal colore piÃ¹ vario (ogni utente ha acqusitato dei vestiti, e guardiamo la lista di colori diversi piÃ¹ lunga)

In [45]:
lista_clienti = acquisti["customer_id"].unique()
lista_clienti

array(['000058a12d5b43e67d225668fa1f8d618c13dc232df0cad8ffe7ad4a1091e318',
       '00007d2de826758b65a93dd24ce629ed66842531df6699338c5570910a014cc2',
       '00083cda041544b2fbb0e0d2905ad17da7cf1007526fb4c73235dccbbc132280',
       ...,
       'fece2f68864c311a0b5208e2eb735b3dcde7e41461d327bdd033014a27168ce8',
       'fee56cc5315dafb35a4490ccc6f711092cae913550c83251955178bdd1bc6be3',
       'ff5b8a8b26bf93a66290e9bd1b73393ac6a58968a7851941508cce49f5dfa469'],
      dtype=object)

In [83]:
colori_clienti = {"id_cliente":[], "numero_colori_differenti":[], "numero_prodotti_acquistati":[]}

# for cliente in lista_clienti:

for i in range(0,100): # da eliminare 
    cliente = lista_clienti[i] # da eliminare
    codici_prodotti_acquistati = acquisti[acquisti["customer_id"] == cliente]["article_id"]
    colori_prodotti_acquistati = articoli[articoli["article_id"].isin(codici_prodotti_acquistati)]["colour_group_name"]
    colori_clienti["id_cliente"].append(cliente)
    colori_clienti["numero_colori_differenti"].append(len(colori_prodotti_acquistati.unique()))
    colori_clienti["numero_prodotti_acquistati"].append(len(codici_prodotti_acquistati))

In [84]:
colori_clienti

{'id_cliente': ['000058a12d5b43e67d225668fa1f8d618c13dc232df0cad8ffe7ad4a1091e318',
  '00007d2de826758b65a93dd24ce629ed66842531df6699338c5570910a014cc2',
  '00083cda041544b2fbb0e0d2905ad17da7cf1007526fb4c73235dccbbc132280',
  '0008968c0d451dbc5a9968da03196fe20051965edde7413775c4eb3be9abe9c2',
  '000aa7f0dc06cd7174389e76c9e132a67860c5f65f970699daccc14425ac31a8',
  '001127bffdda108579e6cb16080440e89bf1250a776c6e55f56e35e9ee029a8d',
  '001ea4e9c54f7e9c88811260d954edc059d596147e1cf8adc73323aebf571fd8',
  '001fd23db1109a94bba1319bb73df0b479059027c182da490e1161b34cd3af61',
  '0021da829b898f82269fc51feded4eac2129058ee95bd75bb1591e2eb14ecc79',
  '00228762ecff5b8d1ea6a2e52b96dafa198febddbc3bf350eb611f28e61ea6ce',
  '002b3c0a44a22c45a8d62ea9d2b88d1a89e335f8b8400335a85c3b5845794cb9',
  '003ac6eff3ca20cbe4e14a106a5e28b7551616005de8f9dd0f9455e5543b31ac',
  '00401a367c5ac085cb9d4b77c56f3edcabf25153615db982fcc7991d182e10a9',
  '00402f4463c8dc1b3ee54abfdea280e96cd87320449eca8953eb06769a5c20d4',
  '0045c79125b4dc958579f902b49eacd8598f9eeaa1220506d1cae1275f122084',
  '004888668b9458668aa3234d17337671673599f7f84d36f77fd366b5139058c5',
  '0051a1d00ec9a4ff1a2f9aa32a4bb054cc9ba08e80be590aec39391ff3dc56e8',
  '005c9fb2ba6c49b2098a662f64a9124ef95cbec5fcf4ebdb4dcbaaf83f979c51',
  '00609a1cc562140fa87a6de432bef9c9f0b936b259ad3075eb2a65008df1dbab',
  '00708c3da4d07706d4cad77c6aecc1b1ce33d21d73022ca12737c91d85bff070',
  '0074c5948b6c96e7522f6f5c034b46cf08875b9a81c557a02bda0aedac355547',
  '00761aefe07a2dd6ca110c99f3856ede55f20ff00ce754bf24c422c6746d05f3',
  '0077ba345ef6aa8781802107df25bbb8a14fdcd04130c3ffa5cd1ac4087ad8ab',
  '00796ce0bc561897e7047a7b059867aa6424f63ec597e1fbb3a195e48d5f452b',
  '007e4c2e0994b4aac97c2713d5dc0b7497d74113f32446868ca22b6437e9594d',
  '007ea762fbbebfad288a49f1d8f7c2c0c62b189a8816fa6968e60f2c197ce938',
  '007f094708bc97c9ce41a7e75237ef2d16ae45319ebaddb9b842abf34248da8f',
  '00873fc0f81215241785b49518e6758a2c26c0eac4825e7eb048b005a33fc3d6',
  '00889357d9b1e0e3788fbe8fd7448580b9e51800f59196891c4796a9aaac0945',
  '008997ffbc4cdb3a41572eb25b2cc918666a6f2a13f3940f196a0160773c8492',
  '008a118b7c72fd3b8a614eb2672ddfc2a78434c5776af215f4e281fa7506b842',
  '0091c0e943c92167ea78f6ac180636be4098b06c1a066cac6f064eab9dc76d3c',
  '00923f88cda50cbea4c5ceb2bd3467c620a9d74cb7da95ccbd21b856f5c0e2e0',
  '0095c9b47fc950788bb709201f024c5338838a27c59c0299b857f94b504cb9fc',
  '00a017d6e1010e117e3881be44027688795bf5f3c363696f7260d0ebe2727285',
  '00a4f2c8cc87ffb0ea7db47b4b0b247b9ef11033c8d976f374f709a6fb80f1b9',
  '00a64e86897e28b304195ad497bc63234a3ab00a5eb247930ff59398d765f04a',
  '00a95aa4ba8d20f1bad415bab15ca6174a762f7550c819f4a1051fc7ee6bcb89',
  '00aa02ce95fc11f654a76101fd39a3db6b29879fddd8f8b1e56b3e6fbe6fe8d8',
  '00ac5119d21281802ecd309e8c7fa0b598e0be861f21caadefd9bc8cf3f87eed',
  '00b10bf5c51e961bd91f7ed9081b1bc6fc7e86000c2bed1a2d9f70da02012432',
  '00b1804e347ad55d1a75d7c07169e17d1890ad48953824879234177741a85955',
  '00b5b1446be091d4913765cf2cc01edc7e0d3820e1b8a46905fa4213a4c24433',
  '00b5bd5358a05155631bf733a933ecff5eb872f5143af59994ff3e62a97476d7',
  '00b6ec8613e51d8eadc5157f5a12ae1366ca29da7d44cc8d0ae1e667dea6f268',
  '00b85712d5e677f7ae3bfa9f9b5780a6eb328e99aeea633f6e8a3df5589d6486',
  '00be0a263381af38132d31225e8fb12fbc527c654b446484fb672a78118f037d',
  '00c09e66121ad36f5a8d5039cda266d60bc53daac0b7ad14f19cbbf97be0b160',
  '00c59bdfaf753688c62cc13f67382dd54275f776a2f6a6ebee11b27049d1d7f7',
  '00c83c269bedcb5135799d3bc4a7ae6f134d57bdd1be071486ef152b2ef1c300',
  '00cd0391b52a160dce983a43c15a6e1125d082b78dfa21dd9fe0ce2f86805b74',
  '00cf4505ba84c01f03c47829352054483acb59a9492ed0eef597dcf030e9e58b',
  '00d316a9b10b3d21094e4931f41a42ec7d093bbbd53c7b656ad830be8e6d1565',
  '00d774cb18ec8f8c73f4a76846782013803b88f206dffd39638a15a8725a886c',
  '00d781e94d9a533dceb85a8d50a898d5987ad9921ea8c6945c247be7220bdd81',
  '00da14cc2ed13b9df1425be332f190877d6607aa7c79f761d7605231fd532814',
  '00e1f75b5a9c8deed486dc2c409329e8aaef117d314e01fe0c08a7300d4d9f03',
  '00e66bb584bb15b519d91b1979bc7ba33fa0ac956000263db19c0036ac8bbb80',
  '00ead79936275fbd3c9cf7863d2eb1b11e553789c48149fec39eb4086cb64642',
  '00f422e9990c411c736a3d0a35a1eea4cdbef1d419fdede13c01eecb99da4176',
  '00ff637ac0fc881ed8b09088ed68218924f87f4100842dbdaf2d26c138fcbf2e',
  '00ffed0316ae807cb9439799d73cd61fd7f6479a0f9a19668ef442e3a775eb63',
  '0115586b1ca570d4a4ef16b9a8e1cf62c9d519d43edc0bc7bdca09b5af2b1370',
  '011d7b691e30ed7eb65d0f141dba11c0d4aa6d30b0625eddc713b7172d4585cf',
  '01271359dce99de537d6a3fca3c4dfd3732b455ec5085dc0b1623ab550fb821a',
  '012bbedf2efe728a7407a5dc842a852f8e09e9ae9727110c916ae13ebbc86395',
  '0132d21d866697c428e4d6ffb02548fd71966aa88c8f5adea314e2341f8ad87b',
  '0137b87739a796f65396d8483173f66318039d19a2583f33f9014a6b6f38719e',
  '01393ee2d1e9494965b723a22d3b09d992a1b450d17621c4c970ef7faf4d0d8c',
  '013a3d7d6d974a818bcb8c5181b4f5016f8973550f42e1049b86053643ace6e2',
  '013cc00a6fe53e361d8b5da4153c5b8907c09bf951dd4ec40d915cf7127c0e6d',
  '013d1d9e3414787ec7bf048697592b6f76dec3bd5263e485e64429ce387ed09c',
  '014838e4a1fadaaaa5bd2504b73861ef89db7a86b1d0b19f0fbd8bcdd5c3f414',
  '014cbfc591254f0cf30df52b660f94dead60c8d3eafc00ebb3051bd196bdcd8e',
  '015379bc0ebfa21c432af0f1eec4cfdd83d88f3af3804fb42011610866da0cba',
  '0157179e65d9394de74d06dd4558456a016a537c55e216a2236b90ac49101d2e',
  '015d779989111f5158d089a639b42390cd864f2001b1ed2f24ad78fd37704271',
  '015e83393e4fc3b071ba6fc5f174bf3bf9813c88dcaf3e61e34c6525984d0ed1',
  '01624a723db9eb160f1ce8148eea035963527b2ddca1816d5cd79b94bd16bd92',
  '0163c83a9a9e6a6653ab4aaf448a2773168cb76e74712456c56ea722df4ee5d8',
  '0164840429884bbb47f2a342ceea1f0748650d632cd7e3ae962169ddc5abc7e7',
  '01657d86ad3c7c5a15c7de441cc0a57c3ed9a3618b368a61aac06070f585df78',
  '016a5e92559854caa17365012de3e26cae632c968dbcc9b0f6343a54223e80b7',
  '016d8f0519d9e0572b3abebeab87408bad7a5c3a2840161f7de2f2900f39b6e6',
  '016ee5d84576b72727d7c812df0080f8fa551ba7156593a5ae585b16608e8077',
  '017ddc94fee40ab9a24af073a4c69282b4c04e094d53a96dc0c97642b5d3b25d',
  '018584209ee49c1e2a461c7773bd642306432ff77eef6f32881c56bb3bf77de6',
  '01887181e59ebbbcda75875d5df516d0ffaa26581ffd78cd909795732e4be9a5',
  '019169333a46eafc04a2a49f04076aeb5bc7f33c403e8940e39048a9581ce753',
  '0193e3d59eb1a5625b36f53e947c0237ee16c4bd2f7ba7da4bb93efb9e17f66a',
  '01959be607170cc2f092ee8fd13eda251b13cde70ef38dd37e37dcdadfde3b9e',
  '0195ffd9003a84142a7fee9fbd85b97f111f054a1ee1587b2b98b60d506a5f1b',
  '01a9a077a83eacc6fd946a60c4ca2aed16219fcd83d31e3110fa04630c42b96d',
  '01b0efc42c236759c44edb9b3c97c9f213d581ce647cf8b16659a9b2eb104df6',
  '01b2ea4635479ad47c3a5eea6659e28f4f5ea16bbb6180bda7a7a3b18cade7bd',
  '01b408ef638888ebabe6ba61e3e9cba93131152d371b50c8aded5eb1ca3aa3c0',
  '01b855043167c672d20955a585f39f590a854238bd78149d4e0802362a40d2de',
  '01bf0506fe8bb4b830a2b0a4459f11565f6b687c615008cdcd59b3abf6df4bd2',
  '01c290bff9641834691fef7f4b68ad176353d6971ca85e22efeb92c3aa3ffd35',
  '01c3653cafdd569ef34e36810d1c1bda71c0d425e568278d0cfe05cfb6604a1a'],
 'numero_colori_differenti': [8,
  29,
  11,
  15,
  12,
  16,
  19,
  16,
  3,
  21,
  18,
  19,
  4,
  4,
  6,
  14,
  17,
  18,
  25,
  6,
  18,
  13,
  1,
  16,
  8,
  7,
  4,
  6,
  18,
  7,
  12,
  20,
  3,
  7,
  12,
  16,
  9,
  21,
  7,
  22,
  5,
  11,
  2,
  25,
  25,
  16,
  16,
  15,
  15,
  3,
  4,
  14,
  26,
  10,
  28,
  23,
  6,
  19,
  33,
  25,
  4,
  18,
  13,
  16,
  24,
  20,
  26,
  16,
  11,
  10,
  1,
  24,
  8,
  6,
  9,
  7,
  1,
  10,
  18,
  20,
  9,
  7,
  2,
  18,
  26,
  28,
  14,
  6,
  3,
  27,
  16,
  21,
  33,
  1,
  17,
  7,
  20,
  14,
  7,
  5],
 'numero_prodotti_acquistati': [18,
  120,
  27,
  61,
  57,
  44,
  42,
  38,
  4,
  78,
  30,
  145,
  11,
  7,
  8,
  48,
  58,
  52,
  288,
  12,
  70,
  76,
  1,
  49,
  17,
  17,
  10,
  6,
  52,
  16,
  37,
  78,
  3,
  16,
  21,
  42,
  24,
  80,
  22,
  77,
  5,
  20,
  2,
  231,
  194,
  123,
  62,
  31,
  93,
  11,
  5,
  81,
  114,
  21,
  184,
  185,
  11,
  68,
  143,
  139,
  21,
  65,
  35,
  24,
  61,
  126,
  181,
  58,
  42,
  37,
  1,
  68,
  27,
  9,
  19,
  16,
  1,
  26,
  110,
  140,
  17,
  33,
  4,
  59,
  104,
  150,
  41,
  9,
  6,
  152,
  83,
  93,
  322,
  1,
  83,
  30,
  115,
  75,
  20,
  22]}

In [85]:
col_clienti_df = pd.DataFrame(colori_clienti)
col_clienti_df

,id_cliente,numero_colori_differenti,numero_prodotti_acquistati
0,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,8,18
1,00007d2de826758b65a93dd24ce629ed66842531df6699...,29,120
2,00083cda041544b2fbb0e0d2905ad17da7cf1007526fb4...,11,27
3,0008968c0d451dbc5a9968da03196fe20051965edde741...,15,61
4,000aa7f0dc06cd7174389e76c9e132a67860c5f65f9706...,12,57
...,...,...,...
95,01b408ef638888ebabe6ba61e3e9cba93131152d371b50...,7,30
96,01b855043167c672d20955a585f39f590a854238bd7814...,20,115
97,01bf0506fe8bb4b830a2b0a4459f11565f6b687c615008...,14,75
98,01c290bff9641834691fef7f4b68ad176353d6971ca85e...,7,20
99,01c3653cafdd569ef34e36810d1c1bda71c0d425e56827...,5,22

In [86]:
n_max = col_clienti_df["numero_colori_differenti"].max() # guardo il numero di colori piÃ¹ grande
lista_persone_n_max = col_clienti_df[col_clienti_df["numero_colori_differenti"] == n_max]["id_cliente"] # guardo il numero di persone che hanno il numero di colori piÃ¹ grande

numero_prodotti_acquistati_piu_piccoli = col_clienti_df[(col_clienti_df["numero_colori_differenti"] == n_max) & (col_clienti_df["id_cliente"].isin(lista_persone_n_max))]["numero_prodotti_acquistati"].min() # guardo il numero piÃ¹ piccolo di vestiti comprati da queste persone

col_clienti_df[(col_clienti_df["id_cliente"].isin(lista_persone_n_max)) & (col_clienti_df["numero_colori_differenti"] == n_max) & (col_clienti_df["numero_prodotti_acquistati"] == numero_prodotti_acquistati_piu_piccoli)]["id_cliente"] # faccio la ricerca con i parametri ottenuti

58    00ead79936275fbd3c9cf7863d2eb1b11e553789c48149...
Name: id_cliente, dtype: object